import { Head } from 'vite-react-ssg';
import { useLocation } from 'react-router-dom';

interface SEOProps {
  title: string;
  description: string;
  keywords?: string;
  canonicalUrl?: string;
  type?: string;
  pageKey?: string; // NEW: key to lookup in seo-data.json for autonomous SEO updates
  structuredData?: object | object[];
  calculatorSchema?: {
    name: string;
    inputs: { name: string; description: string }[];
    outputs: { name: string; description: string }[];
  };
  faqSchema?: { question: string; answer: string }[];
  howToSchema?: {
    name: string;
    steps: { name: string; text: string }[];
    estimatedTime?: string;
  };
  articleSchema?: {
    headline: string;
    author: string;
    datePublished: string;
    dateModified?: string;
    image?: string;
  };
}

const SEO = ({
  title,
  description,
  keywords,
  canonicalUrl,
  pageKey,
  type = "website",
  structuredData,
  calculatorSchema,
  faqSchema,
  howToSchema,
  articleSchema
}: SEOProps) => {
  const siteUrl = 'https://www.thecalculatorpage.com';
  const location = useLocation();

  // Start with provided values
  let finalTitle = title;
  let finalDescription = description;
  let finalKeywords = keywords;

  // Load SEO overrides from seo-data.json if pageKey is provided
  if (pageKey && typeof window === 'undefined') {
    try {
      // Try to load seo-data.json (server-side rendering only)
      // @ts-ignore - seo-data.json is generated by the SEO agent
      const seoDataModule = require('../data/seo-data.json');
      const seoData = seoDataModule.default || seoDataModule;
      const overrides = seoData[pageKey];

      if (overrides) {
        finalTitle = overrides.title ?? title;
        finalDescription = overrides.description ?? description;
        finalKeywords = overrides.keywords ?? keywords;
      }
    } catch {
      // If seo-data.json doesn't exist or can't be loaded, use original values
    }
  } 
  
  // Auto-generate canonical from current route if not explicitly provided
  // This prevents ALL pages defaulting to the homepage canonical
  const autoCanonical = location.pathname === '/'
    ? siteUrl
    : `${siteUrl}${location.pathname}`;

  // Resolve canonical: use explicit if absolute, prepend siteUrl if relative, else auto-generate
  const resolvedCanonical = canonicalUrl
    ? (canonicalUrl.startsWith('http') ? canonicalUrl : `${siteUrl}${canonicalUrl}`)
    : autoCanonical;

  // FIX: Force removal of trailing slash to match sitemap and avoid duplicate errors
  const cleanCanonical = resolvedCanonical.replace(/\/$/, "");

  // Keep full title under 60 chars for SERPs. Use short brand suffix on inner pages.
  const isHomepage = location.pathname === '/';
  const fullTitle = isHomepage
    ? finalTitle
    : `${finalTitle} | CalcPage`;

  // Author schema for E-E-A-T (YMYL financial content)
  const authorSchema = {
    "@type": "Person",
    "name": "Mandeep Singh Duklu",
    "jobTitle": "Financial Coach & Calculator Developer",
    "description": "CeMAP qualified mortgage adviser with 25+ years in UK financial services including Lloyds Banking Group private banking."
  };

  // Base Schema
  const baseSchema = {
    "@context": "https://schema.org",
    "@type": type === "article" ? "Article" : "WebPage",
    "name": finalTitle,
    "description": finalDescription,
    "url": cleanCanonical,
    "author": authorSchema,
  };

  // Combine all schemas into an array
  const allSchemas: any[] = [baseSchema];

  if (structuredData) allSchemas.push(structuredData as any);
  
  if (calculatorSchema) {
    allSchemas.push({
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": calculatorSchema.name,
      "applicationCategory": "FinanceApplication",
      "operatingSystem": "Any",
      "description": description
    });
  }

  if (faqSchema) {
    allSchemas.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": faqSchema.map(faq => ({
        "@type": "Question",
        "name": faq.question,
        "acceptedAnswer": { "@type": "Answer", "text": faq.answer }
      }))
    });
  }

  return (
    <Head>
      {/* Standard Meta Tags */}
      <title>{fullTitle}</title>
      <meta name="description" content={finalDescription} />
      {finalKeywords && <meta name="keywords" content={finalKeywords} />}
      
      {/* CRITICAL FIX: data-rh="true" ensures react-helmet-async 
          replaces the tag instead of duplicating it.
      */}
      <link rel="canonical" href={cleanCanonical} data-rh="true" />
      
      {/* Favicons (Using PNG as specified in your icons fix) */}
      <link rel="icon" type="image/png" href="/favicon.png" />
      <link rel="apple-touch-icon" href="/favicon.png" />

      {/* Social Meta Tags */}
      <meta property="og:type" content={type} />
      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={finalDescription} />
      <meta property="og:url" content={cleanCanonical} />
      <meta property="og:image" content={`${siteUrl}/og-image.svg`} />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={finalDescription} />
      <meta name="twitter:image" content={`${siteUrl}/og-image.svg`} />

      {/* Injecting Structured Data */}
      {allSchemas.map((schema, index) => (
        <script key={`schema-${index}`} type="application/ld+json">
          {JSON.stringify(schema)}
        </script>
      ))}
    </Head>
  );
};

export { SEO };
export default SEO;